### ISSUE TITLE
Shuffle and repeat buttons should follow the color when active

### ISSUE THREAD

**Issue by nicola02nb** [JulienMaille/spicetify-dynamic-theme#100]
**Is your feature request related to a problem? Please describe.**
On normal spotify shuffle and repeat buttons are colored of green when activated and white when not.
On this theme they are ony white and changes color only for a few msec when are clicked.
Normal Spotify:
![image](https://github.com/user-attachments/assets/20ff2873-a7ad-41e5-bb81-e5a43269c54f)
![image](https://github.com/user-attachments/assets/5c49a59b-594d-4d02-9349-7aa1605cef71)

Dynamic Theme version:
![image](https://github.com/user-attachments/assets/2f482837-f912-478c-84b7-815dc11aceac)
![image](https://github.com/user-attachments/assets/1e490519-46de-4ded-8ebd-5c6a4b6e5f29)

**Describe the solution you'd like**
I suggest to put the color of activated buttons to the current accent color....
Something like this should do the job:
``` CSS
.main-nowPlayingBar-center button:not(.main-playPauseButton-button)[aria-checked="true"],
.main-nowPlayingBar-center button:not(.main-playPauseButton-button)[aria-checked="mixed"] {
    color: var(--spice-text) !important;
}
```
![image](https://github.com/user-attachments/assets/d9d937fe-f5a1-4e6d-8ce4-1fdb49736dbd)
![image](https://github.com/user-attachments/assets/a25bf8f9-ae22-4e7b-b9b5-bcff2cc9aa4d)

**Describe alternatives you've considered**
If you want I can PR

**Additional context**
